version: 2
sources:
  - name: fraud_raw
    schema: public
    tables:
      - name: scored_transactions
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 10, period: minute}
          error_after: {count: 1, period: hour}
